spring:
  datasource:
    url: jdbc:mysql://101.132.106.184:3306/questionnaire?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    resources: static-locations: classpath:static/,file:static/
    

mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.code.questionnaireSystem.pojo
  
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql